baseURL = "http://noaahhh.github.io/portfolio"
languageCode = "en-us"
title = "Nuh Yurduseven 's Personal Portfolio"
theme="hugo-theme-shell"
[Params]
  # Note: This is for the meta description, which is different from the "description" displayed in the terminal.
  description = "Nuh Yurduseven Personal Portfolio Page!"
  [Params.Terminal]
  # Note: color schema
  # Note: You can choose between
  # Note: ["monokai", "powershell", "gruvbox_light", "gruvbox_dark", "solarized_light", "solarized_dark", "ubuntu", "retro"]
  # Note: If you want to use the Goph theme, set it to "goph" (See README.md)
  schema = "retro"

  # Note: in terminal
  # [userName]@[pcName]:~/$ cd [workDir]
  # [userName]@[pcName]:~/[workDir]$ cat [profile]
  #
  # [description]
  #
  # Note: if you set Params.Tree > use = true
  # [userName]@[pcName]:~/[workDir]$ tree ./[folderName]/
  # ./[folderName]/
  # ...
  # Note: result of the tree command
  userName = "nuhyurduseven"
  pcName = "portfolio"
  workDir = "mydir"
  profile = "aboutMe"
  email = "nuh_yrdsvn@outlook.com"

  # Note: speed at which text is displayed on the terminal
  # Note: if set to 0, typing animation will be disabled
  # Note:
  # Note: If you want to enable Mathjax, you need to set it to 0
  # Note: and set "math: true" at front matter in your Markdown file
  terminalDelay = 10

  # Note: speed at which text is displayed on the activity pages
  # Note: if set to 0, typing animation will be disabled
  # Note: 
  # Note: If you want to enable Mathjax, you need to set it to 0
  # Note: and set "math: true" at front matter in your Markdown file
  activityDelay = 3

  #description = """
  
  #Hi I am noaahhh!
  #This is my simple portfolio page.

  #I am a computer engineer and MsC software engineering student.
  #Iam interested in  
  #Python and R,
  #Data science and AI,					
  #Operating systems,
  #Finance research about prediction of finacial data...
  
  
  #If you want to reach me , you can click the links 
  #in my_social_accounts directory.
	
  #"""

  # Note: If you want to use a Markdown file, you can use the following
   description = "/description.md"
  # Note: and put the description.md in /content/description.md

  [Params.Tree]
  use = true
  folderName = "my_social_accounts"
  # Note: ["ACTIVITY", "URL or PATH TO YOUR MARKDOWN FILE"]
  files = [ 
    ["Linkedin", "https://www.linkedin.com/in/nuh-yurduseven"],
    ["Twitter", "https://www.twitter.com/noah_the_turk"],
    ["Hashnode","https://noaahhhtech.hashnode.dev"],
    ["Dev.to", "https://dev.to/noaahhh"],
    ["Hackernoon","https://hackernoon.com/u/noaahhh"],
    ["Medium", "https://nuh-yurduseven.medium.com"],
    ["Github", "https://github.com/noaahhh"]
    
  ]
